#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: all_sequences
type: VIEW
columns:
  db_id:
    caseSensitive: false
    dataType: 4
    generated: false
    name: DB_ID
    nullable: false
    primaryKey: false
    unsigned: true
    visible: true
  schema_id:
    caseSensitive: false
    dataType: 4
    generated: false
    name: SCHEMA_ID
    nullable: false
    primaryKey: false
    unsigned: true
    visible: true
  user_id:
    caseSensitive: false
    dataType: 4
    generated: false
    name: USER_ID
    nullable: true
    primaryKey: false
    unsigned: true
    visible: true
  seq_id:
    caseSensitive: false
    dataType: 4
    generated: false
    name: SEQ_ID
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  seq_name:
    caseSensitive: false
    dataType: 12
    generated: false
    name: SEQ_NAME
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  is_cycle:
    caseSensitive: false
    dataType: 16
    generated: false
    name: IS_CYCLE
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  is_order:
    caseSensitive: false
    dataType: 16
    generated: false
    name: IS_ORDER
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  cache_val:
    caseSensitive: false
    dataType: 4
    generated: false
    name: CACHE_VAL
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  curr_val:
    caseSensitive: false
    dataType: -5
    generated: false
    name: CURR_VAL
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  max_val:
    caseSensitive: false
    dataType: -5
    generated: false
    name: MAX_VAL
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  min_val:
    caseSensitive: false
    dataType: -5
    generated: false
    name: MIN_VAL
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  step_val:
    caseSensitive: false
    dataType: -5
    generated: false
    name: STEP_VAL
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  create_time:
    caseSensitive: false
    dataType: 93
    generated: false
    name: CREATE_TIME
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  is_sys:
    caseSensitive: false
    dataType: 16
    generated: false
    name: IS_SYS
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  valid:
    caseSensitive: false
    dataType: 16
    generated: false
    name: VALID
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  comments:
    caseSensitive: false
    dataType: 12
    generated: false
    name: COMMENTS
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  reserved1:
    caseSensitive: false
    dataType: 12
    generated: false
    name: RESERVED1
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  reserved2:
    caseSensitive: false
    dataType: 12
    generated: false
    name: RESERVED2
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  sequence_name:
    caseSensitive: false
    dataType: 12
    generated: false
    name: SEQUENCE_NAME
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
