#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: dba_databases
type: VIEW
columns:
  db_id:
    caseSensitive: false
    dataType: 4
    generated: false
    name: DB_ID
    nullable: false
    primaryKey: false
    unsigned: true
    visible: true
  db_name:
    caseSensitive: false
    dataType: 12
    generated: false
    name: DB_NAME
    nullable: false
    primaryKey: false
    unsigned: true
    visible: true
  user_id:
    caseSensitive: false
    dataType: 4
    generated: false
    name: USER_ID
    nullable: false
    primaryKey: false
    unsigned: true
    visible: true
  char_set:
    caseSensitive: false
    dataType: 12
    generated: false
    name: CHAR_SET
    nullable: true
    primaryKey: false
    unsigned: true
    visible: true
  time_zone:
    caseSensitive: false
    dataType: 12
    generated: false
    name: TIME_ZONE
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  max_user_num:
    caseSensitive: false
    dataType: 4
    generated: false
    name: MAX_USER_NUM
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
