#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: dba_view_columns
type: VIEW
columns:
  db_id:
    caseSensitive: false
    dataType: 4
    generated: false
    name: DB_ID
    nullable: false
    primaryKey: false
    unsigned: true
    visible: true
  view_id:
    caseSensitive: false
    dataType: 4
    generated: false
    name: VIEW_ID
    nullable: false
    primaryKey: false
    unsigned: true
    visible: true
  col_name:
    caseSensitive: false
    dataType: 12
    generated: false
    name: COL_NAME
    nullable: true
    primaryKey: false
    unsigned: true
    visible: true
  col_no:
    caseSensitive: false
    dataType: 4
    generated: false
    name: COL_NO
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  type_name:
    caseSensitive: false
    dataType: 12
    generated: false
    name: TYPE_NAME
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  scale:
    caseSensitive: false
    dataType: 4
    generated: false
    name: SCALE
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  varying:
    caseSensitive: false
    dataType: 16
    generated: false
    name: VARYING
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  comments:
    caseSensitive: false
    dataType: 12
    generated: false
    name: COMMENTS
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  reserved1:
    caseSensitive: false
    dataType: 12
    generated: false
    name: RESERVED1
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  reserved2:
    caseSensitive: false
    dataType: 12
    generated: false
    name: RESERVED2
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
  reserved3:
    caseSensitive: false
    dataType: 12
    generated: false
    name: RESERVED3
    nullable: false
    primaryKey: false
    unsigned: false
    visible: true
